-- https://github.com/clojure-vim/clj-refactor.nvim
-- https://github.com/clojure-vim/acid.nvim
-- https://github.com/clojure-vim/jazz.nvim
-- https://github.com/jebberjeb/clojure-socketrepl.nvim
-- https://github.com/jamesnvc/clj.nvim
-- https://github.com/WildUtah/nvim-setup-for-clojure
