--
--
--
--
--  so i should try using the path lib and see how it works and see if I can get
--   bit more comfortable with lua and nvim this way. plenary is quite an advanced
--   library
--   and there is very little documentation. I mean, you just have to read through
--   the code and see what is there. it is a very well written project that
--   gives you everything that you need in order to do quite advanced things inside
--   of neovim.
