-- TODO: try this !!! https://github.com/contour-terminal/contour
--

-- TODO: mollewei.de host blog based on neorg

-- TODO: install asahi linux and try dorothy.

-- how much memory do I have and can I transition to linux right now today?
--
-- this is very cool. this could allow me to start working on my wm
-- management.
--

-- NOTE: kolla upp veckonummer.

-- TEST: Hallå i sommar hur har du tänkt. Ska du vara ledig några speciella
-- dagar eller har du veckor där du inte vill jobba osv?

-- HACK:
-- Tjabba,
-- Du, det aer framfor allt datumen 26-29 Maj som jag behover vara ledig och sista
-- veckan i Juli. Utover det aer jag jaette flexibel.
--
-- Det
--
-- it is h
-- zb
--
-- and actually have a chance to have proper ajudication.
-- and harm yourself or others.
-- it is an impossible situation that they cannot really do. and all of the
-- bs bureacracy that doesn't really add any immediate value.
--
-- okay so the reaper forum can give me anything that I like and it will become
-- quite a fucking awesome thing that would never fucking do that shit in
-- the old state you know and so therefore it is something that is just stupid.
--
-- this is amazing becase this could allow me to really use mac machines
-- in a way that is just amazingly good.
--
-- this is pretty cool and this also teaches me about linux because I
-- always have two systems to compare which actually would make learning
-- faster right?
--
-- spreading the antivax narrative. no that is all wrong. that is a narrative
-- in its own that allows for more easilly pushing skepticism under the rug,
-- when an tinfoil lens already has been laid onto anyone who digs up real
-- information.
--
-- and this could be pretty great and it would allow for me to run this
-- and
-- just test and see if i can run kmonad at all
--
-- im just pure and good and it is the funniest thing ever that they subscribe
-- to it.
--
-- by saying he he gets the name that he wanted and he wanted to be a he even
-- though he is a biological female. all this confusion around sex is just a
-- way of complicating stuff that doesn't matter so that you waste energy and
-- iq development on things that have no real value in the end.
--
-- and so when that is brought forth that will mean that they can run this
-- shit and then pull like a master.
--
-- this is pretty fucking based since this is such an immensely powerful
-- os, and it gives for a much better dev experience, especially if you
-- are a vim user. everything is expected to run on linux but on macos
-- you are always a second class citizen.
--
-- yes she is taken for the swedish national team and that is pretty fucking
-- amazing and we will do that shit nad then run this system and see
-- what happens and then run it around and then jump up on the other side
-- that they have the other sysetm that is also a linux machine but
--
--
-- today i should really install vite and get moving with the pitch machine project
--
-- this is very interesting and i should add all of these into my leg routine
-- so that I can do a lot of this shit and always warm uf with some of that.
--
-- all of these leg exercises should be able to make me free from this shit.
-- i can feel now that so many things are happening in my torso because
-- of the leg exercises tha I do but i am still a little bit confused still.
--
-- we used to be the april fools day master and ive had some hal of fame
-- prices since this. it just doesn't work anymore andit is just not fun
-- anymore.
--
-- om jag kan fao det att fungera pao mac that would be quite amazing because
-- at least then I can run linux natively which will be fast. and I
-- will be able to hopefully map stuff to kmonad and run command
-- which means that I will able to fully leverage kmonad, which would be
-- fucking amazing and so that is the reason why that would be
-- the best.
--
-- he has said that he believes this is just the beginning and he has gone
-- over to the jail and which would make it so impossible to run that
--
-- graham potter is fired from his position in londons chelsea
--
-- it is important that we get to know what the fuck is going on you know.
--
-- so this is a bit annoying and I will see if this will work at all in the
-- end.
--
-- these 8 exercises for legs are quite fucking hard to do perfectly.
-- none of them can be done perfectly by a beginner nad so it is important
-- to do all of these regularly. some of them you can do at home.
-- but some of them require a little bit more load and so weights or a
-- bar are necessary.
--
-- now this is cool and hopefully i will get this to work so that I can
-- move on to just playing around with vite and then include
-- next js or some more fancy stuff, and eventually maybe be able to
-- migrate over to remix or something.
--
-- 1. breda squats / adductor
--
-- 2. abductor side lifts
--
-- 3. teardrops (dip knees in/out)
--
-- 4. hamstring
--
-- 5. clean/jerk/snatch (DL/squats)
--
-- 6. jefferson
--
-- 7. split squats
--
-- 8. calves
--
-- this is cool because now I have access to the chatgpt 4 version
-- which means that I can build my own applications with it and then
-- maybe use it in my pitch machine application. maybe it could
-- generate music and melodies. at least I could try to use it and see
-- what happens since it is a great learning experience and will
-- always keep some things for free for the users
--
-- it is super annoying that it still feels this locked up.
