-- TODO: * DEPENDENCIES
--   I need to bump dependencies and make sure that every thing works.
--   - https://docs.npmjs.com/cli/v6/configuring-npm/package-json
--   - https://www.letsreact.org/package-json-explained/
--   check each package on NPM and see which is the latest version and then
--   slowly upgrade each instance.
-- *** articles on upgrading
--     ~  https://stackoverflow.com/questions/56481676/how-to-update-pre-existing-dependency-when-using-create-react-app
--     ~  https://create-react-app.dev/docs/updating-to-new-releases/
--     ~  https://www.geeksforgeeks.org/how-to-update-dependency-in-package-json-file/

-- TODO: CONVERT FROM JS TO TYPESCRIPT
--        -- 22/23
--        https://www.scien.cx/2022/11/29/how-to-migrate-your-react-project-to-typescript/
--        https://betterprogramming.pub/should-you-switch-to-typescript-yes-73bd517ff74d
--
--        gatsby: https://blog.logrocket.com/incrementally-migrate-gatsby-app-typescript/
--
--        -- A BIT OLD
--          https://www.sitepoint.com/how-to-migrate-a-react-app-to-typescript/
--
--        https://duckduckgo.com/?q=convert+create+react+app+to+typescript&ia=web
--
--
--        curious -> prop-types vs typescript (https://www.youtube.com/watch?v=kOB0PcVEuZg)
--
--

-- TODO: improve sass structure
--    sass -> file structure: https://dev.to/dostonnabotov/a-modern-sass-folder-structure-330f
